version: "3.9"

services:
  db:
    container_name: "mongo"
    image: "mongo"
  
  logic:
    container_name: "node"
    image: "node"

  server:
    container_name: "server"
    image: "nginx"
    ports:
    - 1234:8080