version: "3.9"

services:
  db:
    container_name: "mongo_server"
    image: "mongo"
  
  app:
    container_name: "node_app"
    image: "node"

  login:
    container_name: "login_server"
    image: "nginx"
    ports:
    - 1234:80